#define g 			d_g
#define env77			d_env77
#define TypeList		d_TypeList
#define VaiableStorage		d_VaiableStorage
#define dsqrt			dd_sqrt
#define datan			dd_atan
#define dsin			dd_sin
#define dcos			dd_cos
#define dfabs			d_fabs
#define dprintf			d_printf
#define dfprintf		d_fprintf
#define dfopen			d_fopen
#define dfclose			d_fclose
#define dfree			d_free
#define dmalloc			d_malloc
#define dputchar		d_putchar
#define dgetchar		d_getchar
#define ftoap			d_ftoap
#define _print			d_print
#define new_line		d_new_line
#define runCode			d_runCode
#define runEnd			d_runEnd
#define doSpace			d_doSpace
#define doBackPatch		d_doBackPatch
#define doCS			d_doCS
#define doDS			d_doDS
#define getlab			d_getlab
#define putInt			d_putInt
#define putlab			d_putlab
#define manageBC		d_manageBC
#define manageSW		d_manageSW
#define putLong			d_putLong
#define strsave			d_strsave
#define tree			d_tree
#define startEval		d_startEval
#define endEval			d_endEval
#define evalDone		d_evalDone
#define Eval			d_Eval
#define runCode			d_runCode
#define RunEnd			d_RunEnd
#define find_sym		d_find_sym
#define findSymbol		d_findSymbol
#define findStructures	d_findStructures
#define doExternals		d_doExternals
#define doLocals		d_doLocals
#define doSubroutine	d_doSubroutine
#define freeVSTree		d_freeVSTree
#define freeTTree		d_freeTTree
#define freeCTree		d_freeCTree
#define zerol			d_zerol
#define yyparse			d_yyparse
#define zerol			d_zerol
#define zerol			d_zerol
